.Dd August 17, 2014
.Dt PICK 1
.Os
.Sh NAME
.Nm pick
.Nd fuzzy select anything
.Sh SYNOPSIS
.Nm pick
.Op Fl h
.Op Fl v
.Op Fl q Ar QUERY
.Sh DESCRIPTION
.Nm pick
allows users to select from a set of choices using an
.Xr ncurses 3X
interface with fuzzy search functionality.
.Pp
.Nm pick
accepts a list of choices as input and produces the selected choice as output.
.Pp
.Nm pick
supports these options and arguments:
.Bl -tag -width "\&-q QUERY"
.It Fl h
display a help message and exit.
.It Fl v
display the version and exit.
.It Fl q Ar QUERY
supply an initial search query.
.El
.Pp
The
.Nm pick
.Xr ncurses 3X
interface is operated with the following keys:
.Bl -tag -width Backspace
.It Ic "Up\&/Down"
Select between choices matching the current search query.
.It Ic Enter
Output the currently selected choice and exit.
.It Ic "Printable characters"
Printable characters are added to the search query input field and will refine
the current search query.
.It Ic "Left\&/Right or Ctrl\&-B\&/Ctrl\&-F"
Move the cursor left and right in the search query input field.
.It Ic "Ctrl\&-A"
Move the cursor to the beginning of the line in the search query input field.
.It Ic "Ctrl\&-E"
Move the cursor to the end of the line in the search query input field.
.It Ic Backspace
Delete one character to the left of the cursor in the search query input field.
.It Ic "Ctrl\&-D"
Delete the character under the cursor in the search query input field.
.It Ic "Ctrl\&-W"
Delete to the beginning of the closest word to the left in the search query
input field.
.It Ic "Ctrl\&-U"
Delete to the beginning of the line in the search query input field.
.It Ic "Ctrl\&-K"
Delete to the end of the line in the search query input field.
.El
.Sh EXAMPLES
.Nm pick
can be used to select anything and is very effective when combined with
utilities like
.Xr xargs 1 .
.Pp
Select a file in the current directory to open using
.Xr xdg-open 1 :
.Bd -literal -offset indent
find -type f | pick | xargs xdg-open
.Ed
.Sh AUTHORS
.An "Calle Erlandsson" Aq calle@thoughtbot.com
.An "thoughtbot" Aq hello@thoughtbot.com
